### ISSUE TITLE
SyntaxError: Unexpected token import

### ISSUE THREAD

**Issue by auhgnep** [tralves/nativescript-vue-rollup-template#13]
Hi, I have a problem!
tns run android
Searching for devices...
Skipping prepare.
Refreshing application...
Successfully synced application org.nativescript.hellonsrollvue on device emulator-5554.
ActivityManager: Start proc 10598:org.nativescript.hellonsrollvue/u0a82 for activity org.nativescript.hellonsrollvue/com.tns.NativeScriptActivity
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
System.err: 
System.err: Cannot compile /data/data/org.nativescript.hellonsrollvue/files/app/main.js
System.err: 
System.err: SyntaxError: Unexpected token import
System.err: File: "file:///data/data/org.nativescript.hellonsrollvue/files/app/main.js, line: 1, column: 60
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'require', file:'', line: 1, column: 266

**Comment by tralves** [comment]
Hi!

As you can see in the README file, this project is deprecated and no longer maintained. I strongly recommend using the vue-cli-template as described in the official docs.

The problem here is that you are missing a `cd tns`, as described in the README.
