### ISSUE TITLE
missing some files after creat app from the template

### ISSUE THREAD

**Issue by SkyGrass** [tralves/nativescript-vue-rollup-template#3]
hi  ,i try to create app from the template . but , i find that i missing .vue files in the app folder.

![wx20171104-005235](https://user-images.githubusercontent.com/10251029/32385900-8baadd5a-c08d-11e7-8251-91154b1ebae8.png)

`SkyGrassdeiMac:desktop skygrass$ tns create mysecondapp  --template https://github.com/tralves/nativescript-vue-webpack-template
Installing  https://github.com/tralves/nativescript-vue-webpack-template
+ nativescript-vue-webpack@0.1.0
added 117 packages in 19.815s
+ tns-template-hello-world@3.3.0
added 1 package in 2.255s
Installing  tns-core-modules
+ tns-core-modules@3.3.0
updated 1 package in 2.823s

> fsevents@1.1.2 install /Users/skygrass/Desktop/mysecondapp/node_modules/fsevents
> node install

[fsevents] Success: "/Users/skygrass/Desktop/mysecondapp/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
added 601 packages in 16.788s
Project mysecondapp was successfully created.`

**Comment by SkyGrass** [comment]
sorry,i fixed it ,i should install nvativescript-vue first . sorry about it.
i want to know that whether the template will continue  be update.

**Comment by tralves** [comment]
Hi!

I am glad you figured it out. I really think that webpack will eventually replace this template. But don't worry, I will write a nice upgrade guide so you can move your project to webpack.
