### ISSUE TITLE
unexpected token < at App.vue

### ISSUE THREAD

**Issue by krunaldodiya** [tralves/nativescript-vue-rollup-template#4]
file:///app/components/App.vue:1: JS ERROR SyntaxError: Unexpected token '<'

**Comment by seohangyu** [comment]
i have same issue

**Comment by tralves** [comment]
Please make sure you are running `tns debug android/ios` **inside** the `tns` folder.

I need to get rid of that folder. It confuses a lot of people...

**Comment by krunaldodiya** [comment]
thanks, finally done inside tns folder :)

**Comment by seohangyu** [comment]
Are you telling me to remove 'tns folder' and run tns run android?

**Comment by tralves** [comment]
@seohangyu no! I am telling you to run `tns run android` inside the tns folder.

That other comment was about future work on this template. The `tns` folder confuses people. Is want to find a way so that it is no longer necessary.

**Comment by seohangyu** [comment]
a.. thanks! :D
