### ISSUE TITLE
Including custom fonts

### ISSUE THREAD

**Issue by 34r7h** [tralves/nativescript-vue-rollup-template#5]
Hi, thanks for taking the time to make this. Having .vue files and es6 import is a huge win!

When I add a font folder with custom font and set a family in css, the fonts don't render although the inspector says the font is there. Any idea if rollup could be overriding render somehow?

Works out-of-the-box with standard nativescript-vue.

**Comment by 34r7h** [comment]
Problem was not adding the font-folder manually to the tns/app folder.

**Comment by tralves** [comment]
ah, that... 99% of issues are related to the `tns` folder... I gotta find a way to get rid of it...
