### ISSUE TITLE
 I want to add an image, in which path should I add it?

### ISSUE THREAD

**Issue by seohangyu** [tralves/nativescript-vue-rollup-template#7]
I want to add an image, in which path should I add it?

**Comment by tralves** [comment]
Hi!

This page explains better than I would: https://docs.nativescript.org/ui/images.
Ex. add an image to `tns/app/imgs/myimg.jpg`, then access it in your code ex: `<image src="~/imgs/myimg.jpg">`
In the [Groceries app](https://github.com/tralves/groceries-ns-vue) I load all images from a resource files.

**Comment by seohangyu** [comment]
Thank you very much ... I wasted a lot of time and I was able to solve it thanks to you.
