### ISSUE TITLE
Failed to find module:"./components/App.vue"

### ISSUE THREAD

**Issue by Lavhe** [tralves/nativescript-vue-rollup-template#8]
I don't know what i am doing wrong but this is the error i have been getting.

**Comment by tralves** [comment]
Please run `tns debug android/ios` inside the `tns` folder.

**Comment by Lavhe** [comment]
Thank and now i get  "Execution failed for task ':buildMetadata'." if i run it inside the tns folder

**Comment by tralves** [comment]
I need more context. Can you send the entire log or take a picture of the error?

**Comment by Lavhe** [comment]
![screenshot_20171201_003308](https://user-images.githubusercontent.com/13318139/33458540-438123d8-d62f-11e7-82fe-8ccab97d5352.png)

**Comment by Lavhe** [comment]
OHK I solved the problem,  i just deleted the entire folder and created a brand new project

Maybe i messed up some configs while trying to solve the first problem

THANK YOU VERY MUCH.
